### ISSUE TITLE
Does not work with ceph-jewel

### ISSUE THREAD

**Issue by acehege** [ClusterHQ/ceph-flocker-driver#10]
It seems that this storage driver currently only works on ceph-infernalis and not ceph-jewel.

I can have a look and try and clean up and fix the problem.

I have forked the repo and will try and fix it during the weekend :)
## Does not work

``` bash
acehege@docker001:~$ ceph --version
ceph version 10.2.2 (45107e21c568dd033c2f0a3107dec8f0b0e58374)
```

``` bash
acehege@lspdocker001:~$ sudo cat /etc/flocker/agent.yml
"version": 1
"control-service":
   "hostname": "docker001"

"dataset":
    "backend": "ceph_flocker_driver"
    "user_id": "ceph"
    "cluster_name": "ceph"
    "ceph_conf_path": "/etc/ceph/ceph.conf"
```
## Works

``` bash
acehege@docker002:~$ ceph --version
ceph version 9.2.1 (752b6a3020c3de74e07d2a8b4c5e48dab5a6b6fd)
```

``` bash
acehege@docker002:~$ sudo cat /etc/flocker/agent.yml
"version": 1
"control-service":
   "hostname": "docker001"

"dataset":
    "backend": "ceph_flocker_driver"
    "user_id": "ceph"
    "cluster_name": "ceph"
    "ceph_conf_path": "/etc/ceph/ceph.conf"
```

**Comment by eesprit** [comment]
As version 0.14.0 of flocker is out, and it adds support to ubuntu 16.04 which has ceph in version 10.2.2, adding support for it seems quite important now.
Not sure about the proposed patch, it might break compatibility with older ceph releases. Better to add a check to get the installed version and adapting the commands depending on it.

**Comment by acehege** [comment]
@eesprit, i agree that patch breaks support for CEPH older then 10.2.2, but I think @ClusterHQ needs to chime in and decide if they should;
1. Support only 10.2.2 and higher
2. Or support both old and newer versions.

Since this driver is not yet marked for production, it would be great to hear from @ClusterHQ on how much work they want to put into this driver.
I have tested the driver now in some different scenarios, and really looking forward to hearing more from @ClusterHQ regarding the future of the driver, since it is really holding its weight in tests :+1:

**Comment by acehege** [comment]
@eesprit, I decided to ditch flocker/ceph-plugin and instead just use [Docker-volume-netshare ](https://github.com/ContainX/docker-volume-netshare) instead. 
So I am no going to be looking into this storage driver anymore.
