### ISSUE TITLE
Ceph python dependencies are difficult to access

### ISSUE THREAD

**Issue by robhaswell** [ClusterHQ/ceph-flocker-driver#3]
Ceph supplies two Python libraries: `rbd.py` and `rados.py`. On Ubuntu, these are installed into `/usr/lib/python2.7/dist-packages` and provided by the packages `python-rados` and `python-rbd`.

Flocker operated in a virtualenv at `/opt/flocker`. This prevents Flocker from accessing these libraries. Unfortunately this driver requires them.

**Comment by PiotrProkop** [comment]
Hi, i think this pull request can help you (https://github.com/ClusterHQ/ceph-flocker-driver/pull/4).

**Comment by robhaswell** [comment]
Thanks! I'm hopeful that `python-cephlibs` is the answer to this! I'm just spinning up a cluster to test your PR now.

**Comment by PiotrProkop** [comment]
Was it helpful ?

**Comment by robhaswell** [comment]
Still trying to get a cluster spun up haha. I'm using this opportunity to beta-test our upcoming CloudFormation-based installer. I managed to get a spinup working today though so I will be able to test this afternoon :) sorry for the delay!

**Comment by robhaswell** [comment]
Hi Piotr, I haven't forgotten about this, it's just difficult to find time to work on it right now for me, however somebody else at ClusterHQ picked up this project yesterday so expect a reply soon!
