### ISSUE TITLE
Flocker failed after running for some time

### ISSUE THREAD

**Issue by aisensiy** [ClusterHQ/ceph-flocker-driver#7]
Currently, I am using flocker ceph and mesos together. And I use flocker and ceph as the storage solution for my mesos cluster. 

But it seems that flocker does not work stable enough. The command 

`docker run --volume-flocker=ceph -v xxx:/xxx some-image`

may get blocked and show message `Timed out waiting for dataset to mount.` I checked the log of flocker and I still don't know the reason. The json format log is really hard to understand.

I have multi flocker agent running. And only one of them failed to run container with flocker as volume driver. Others work fine.

**Comment by arthurtsang** [comment]
any luck?  i just setup flocker ceph and the one with the flocker-control doesn't work but the other two works fine.

**Comment by aisensiy** [comment]
@arthurtsang I don't use flocker any more. I use rbd-block-plugin now. It is not as flexible as flocker but it is quite stable. No control is needed.

**Comment by arthurtsang** [comment]
this? https://github.com/yp-engineering/rbd-docker-plugin

**Comment by aisensiy** [comment]
@arthurtsang  Yep, but it still have some bugs when working with multi-machines. I am trying to fix it.
