### ISSUE TITLE
How's this driver coming along - I'm excited to see it released!

### ISSUE THREAD

**Issue by far-blue** [ClusterHQ/ceph-flocker-driver#8]
As per the title - I'm really interested in seeing this driver make it to release. How's it going and is it likely to be out of WIP soon?

**Comment by wallnerryan** [comment]
Hi @far-blue thank you for your interest, I will bring this feedback to our product team

**Comment by far-blue** [comment]
There appears to have been no movement on this for over a month. Is it still happening or is it being shelved? totally understand if it's not being progressed, would just like to know either way :)

**Comment by chengweiv5** [comment]
@far-blue +1

**Comment by ferrantim** [comment]
hey @far-blue and @chengweiv5 We are still planning on fully supporting Ceph.  Right now, what is missing is integration testing with the rest of the Flocker codebase.  We want to add that before we call this driver done.  But without that testing, it is still usable.  There is nothing planned functionality wise before we remove the experimental label so hopefully that helps.

**Comment by far-blue** [comment]
Thanks for letting us know the status :) I'll continue experimenting but I'm sure you understand while the code is still labelled experimental I'll hold off on production use :)

**Comment by far-blue** [comment]
It's been a while since there's been any movement on this plugin now - is it still going anywhere?

**Comment by galindro** [comment]
@ferrantim @wallnerryan

Any news?

**Comment by far-blue** [comment]
I don't think we can expect any further progress because ClusterHQ have shutdown

**Comment by ferrantim** [comment]
Yeah, unfortunately @galindro, ClusterHQ is no more.

**Comment by wallnerryan** [comment]
@far-blue @galindro you may be able to find more support at https://github.com/ScatterHQ/flocker where there are a few engineers willing to help support if there is a _real_ need via consulting

**Comment by galindro** [comment]
Tks @wallnerryan , but as soon ClusterHQ was out, I'm moving to [rex-ray](rexray.readthedocs.io/).

**Comment by wallnerryan** [comment]
Good luck!
